version: '3'

tasks:
  # development
  test:
    dir: worker
    cmds:
      - go test -cover ./...
  build-darwin:
    dir: worker
    cmds:
      - go build -o ./bin/darwin ./...
  # update system setting files
  update-wezterm:
    dir: worker
    cmds:
      - ./bin/darwin/wezterm
  update-nvim:
    dir: worker
    cmds:
      - ./bin/darwin/nvim
  update-nix:
    dir: worker
    cmds:
      - ./bin/darwin/nix
  update-zsh:
    dir: worker
    cmds:
      - '[ -f "$ZSH/lib/directories.zsh" ] && rm "$ZSH/lib/directories.zsh" || echo "$ZSH/lib/directories.zsh does not exist"'
      - ./bin/darwin/zsh
  # downloader
  install-font:
    cmds:
      - bash ./downloader/font_downloader.sh
  install-jetpack:
    cmds:
      - bash ./downloader/jetpack_downloader.sh
