version: '3'

tasks:
  test:
    dir: worker
    cmds:
      - go test -cover ./...
  flake:
    dir: flake
    cmds:
      - nix flake check --all-systems
  wezterm:
    dir: worker
    cmds:
      - go run entry_point/wezterm/main.go
  nvim:
    dir: worker
    cmds:
      - go run entry_point/nvim/main.go
  nix:
    dir: worker
    cmds:
      - go run entry_point/nix/main.go
  zsh:
    dir: worker
    cmds:
      - go run entry_point/zsh/main.go
  font:
    cmds:
      - bash ./downloader/font_downloader.sh
  jetpack:
    cmds:
      - bash ./downloader/jetpack_downloader.sh
