version: '3'

tasks:
  # development
  test-worker:
    dir: worker
    cmds:
      - go test -cover ./...
  build-darwin:
    dir: worker
    cmds:
      - go build -o ./bin/darwin ./...
  # update system setting files
  update-wezterm:
    dir: worker
    cmds:
      - ./bin/darwin/wezterm
  update-nvim:
    dir: worker
    cmds:
      - ./bin/darwin/nvim
  update-nix:
    dir: worker
    cmds:
      - ./bin/darwin/nix
  update-zsh:
    dir: worker
    cmds:
      - |
        if [ -f "$ZSH/lib/directories.zsh" ]; then
          rm "$ZSH/lib/directories.zsh"
          echo "Removed $ZSH/lib/directories.zsh"
        fi
      - ./bin/darwin/zsh
  # downloader
  font:
    cmds:
      - bash ./downloader/font_downloader.sh
  jetpack:
    cmds:
      - bash ./downloader/jetpack_downloader.sh
