version: '3'

tasks:
  test:
    dir: worker
    cmds:
      - go test -cover ./...
  wezterm:
    dir: worker
    cmds:
      - go run entry_point/wezterm/main.go
  nvim:
    dir: worker
    cmds:
      - go run entry_point/nvim/main.go
  zsh:
    dir: worker
    cmds:
      - go run entry_point/zsh/main.go
  hello:
    dir: worker
    cmds:
      - go run entry_point/hello/main.go
