version: '3'

tasks:
  # development
  test:
    dir: worker
    cmds:
      - go test -cover ./...
  darwin-build:
    dir: worker
    cmds:
      - go build -o ./bin/darwin ./...
  # nix flake
  flake:
    dir: flake
    cmds:
      - nix flake check --all-systems
  # update system setting files
  wezterm:
    dir: worker
    cmds:
      - ./bin/darwin/wezterm
  nvim:
    dir: worker
    cmds:
      - ./bin/darwin/nvim
  nix:
    dir: worker
    cmds:
      - ./bin/darwin/nix
  zsh:
    dir: worker
    cmds:
      - ./bin/darwin/zsh
  # downloader
  font:
    cmds:
      - bash ./downloader/font_downloader.sh
  jetpack:
    cmds:
      - bash ./downloader/jetpack_downloader.sh
