vim.cmd('syntax enable')  -- Enable syntax highlighting
vim.g.nobackground = 1  -- Disable background
vim.opt.autoindent = true  -- Enable auto indentation
vim.opt.autoread = true  -- Automatically reload files if changed externally
vim.opt.backup = false  -- Disable creation of backup files
vim.opt.clipboard = "unnamedplus"  -- Yank to clipboard
vim.opt.compatible = false  -- Disable compatibility with vi
vim.opt.cursorcolumn = true  -- Highlight the current column
vim.opt.cursorline = true  -- Highlight the current line
vim.opt.encoding = "UTF-8"  -- Set file encoding to UTF-8
vim.opt.expandtab = true  -- Convert tabs to spaces
vim.opt.fileencoding = "utf-8"  -- Set the file encoding to UTF-8
vim.opt.hidden = true  -- Allow switching buffers without saving
vim.opt.hlsearch = true  -- Highlight search results
vim.opt.ignorecase = true  -- Ignore case when searching
vim.opt.incsearch = true  -- Show search matches as you type
vim.opt.laststatus = 2  -- Always show the status line
vim.opt.mouse = ""  -- Disable Click
vim.opt.number = true  -- Display line numbers
vim.opt.shiftwidth = 2  -- Set the width of an indentation level to 2 spaces
vim.opt.showcmd = true  -- Show incomplete commands
vim.opt.showmatch = true  -- Highlight matching brackets
vim.opt.smartcase = true  -- Enable case-sensitive searching when uppercase letters are used
vim.opt.smartindent = true  -- Enable smart indentation
vim.opt.swapfile = false  -- Disable creation of swap files
vim.opt.tabstop = 2  -- Set the width of a tab to 2 spaces
vim.opt.termguicolors = true  -- Enable true color support
vim.opt.title = true  -- Set the terminal title
vim.opt.virtualedit = "onemore"  -- Allow cursor to move past the end of line
vim.opt.visualbell = true  -- Use visual bell instead of beeping
vim.opt.wildmode = "list:longest,full"  -- Use longest partial completion
vim.opt.wrapscan = true  -- Search wraps around the end of the file
