version: '3'

vars:
  VERSION: 0.0.2

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:default:arm:
    desc: "build neovim-docker-default-arm"
    dir: neovim-docker-default-arm
    cmds:
      - docker build -t neovim-docker-default-arm .
    silent: true

  run:default:arm:
    desc: "run neovim-docker-default-arm (need build:default:arm before run this)"
    cmds:
      - bash ./entry_point.sh neovim-docker-default-arm {{.CLI_ARGS}}
    silent: true

  build:default:amd:
    desc: "build neovim-docker-default-amd"
    dir: neovim-docker-default-amd
    cmds:
      - docker build -t neovim-docker-default-amd .
    silent: true

  run:default:amd:
    desc: "run neovim-docker-default-amd (need build:default:amd before run this)"
    cmds:
      - bash ./entry_point.sh neovim-docker-default-amd {{.CLI_ARGS}}
    silent: true

  build:python:
    desc: "build neovim-docker-python"
    dir: neovim-docker-python
    cmds:
      - docker build -t neovim-docker-python .
    silent: true

  run:python:
    desc: "run neovim-docker-python (need build:python before run this)"
    cmds:
      - bash ./entry_point.sh neovim-docker-python {{.CLI_ARGS}}
    silent: true

  push:
    desc: "build and push all containers"
    cmds:
      - task push:default:arm
      - task push:default:amd
      - task push:python

  push:python:
    desc: "build and push neovim-docker-python"
    dir: neovim-docker-python
    cmds:
      - docker build -t neovim-docker-python .
      - docker tag neovim-docker-python tsuchiya55docker/neovim-docker:python-{{.VERSION}}
      - docker push "tsuchiya55docker/neovim-docker:python-{{.VERSION}}"
    silent: true

  push:default:arm:
    desc: "build and push neovim-docker-default"
    dir: neovim-docker-default-arm
    cmds:
      - docker build -t neovim-docker-default-arm .
      - docker tag neovim-docker-default-arm tsuchiya55docker/neovim-docker:default-arm-{{.VERSION}}
      - docker push "tsuchiya55docker/neovim-docker:default-arm-{{.VERSION}}"
    silent: true

  push:default:amd:
    desc: "build and push neovim-docker-default"
    dir: neovim-docker-default-amd
    cmds:
      - docker build -t neovim-docker-default-amd .
      - docker tag neovim-docker-default-amd tsuchiya55docker/neovim-docker:default-amd-{{.VERSION}}
      - docker push "tsuchiya55docker/neovim-docker:default-amd-{{.VERSION}}"
    silent: true
