{ config, pkgs, lib, ... }:

{
  # programs.firefox is not used due to symlink issues on macOS
  # Instead, we use home.file to deploy user.js directly as a real file

  # Deploy user.js as a real file (not symlink)
  home.file."Library/Application Support/Firefox/Profiles/default/user.js" = {
    text = ''
      // Generated by Home Manager

      // Language
      user_pref("intl.accept_languages", "en-US, en");

      // Theme
      user_pref("browser.theme.selected", "firefox-compact-dark@mozilla.org-2");
      user_pref("browser.in-content.dark-mode", true);

      // Wallpaper features
      user_pref("browser.newtabpage.activity-stream.newtabWallpapers.enabled", true);
      user_pref("browser.newtabpage.activity-stream.newtabWallpapers.v2.enabled", true);
      user_pref("browser.newtabpage.activity-stream.newtabWallpapers.customWallpaper.enabled", true);
      user_pref("browser.newtabpage.activity-stream.newtabWallpapers.customColor.enabled", true);
    '';
  };

  # NOTE: profiles.ini is managed by Firefox automatically
  # NOTE: The following must be configured manually in Firefox UI (one-time):
  # 1. Search Engine: Settings → Search → Default: DuckDuckGo
  # 2. Extensions: https://addons.mozilla.org/firefox/addon/bitwarden-password-manager/
  # 3. Sidebar: Settings → Sidebar → Enable vertical tabs, position: right
}
