version: '3'

vars:
  VERSION: 0.0.1

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:default:
    desc: "build akatsuki-default"
    dir: akatsuki-default
    cmds:
      - docker build -t akatsuki-default .
    silent: true

  run:default:
    desc: "run akatsuki-default (need build:default before run this)"
    cmds:
      - bash ./entry_point.sh akatsuki-default {{.CLI_ARGS}}
    silent: true

  build:python:
    desc: "build akatsuki-python"
    dir: akatsuki-python
    cmds:
      - docker build -t akatsuki-python .
    silent: true

  run:python:
    desc: "run akatsuki-python (need build:python before run this)"
    cmds:
      - bash ./entry_point.sh akatsuki-python {{.CLI_ARGS}}
    silent: true

  push:
    desc: "build and push all containers"
    cmds:
      - task push:default
      - task push:python


  push:python:
    desc: "build and push akatsuki-python"
    dir: akatsuki-python
    cmds:
      - docker build -t akatsuki-python .
      - docker tag akatsuki-python tsuchiya55docker/akatsuki:python-{{.VERSION}}
      - docker push "tsuchiya55docker/akatsuki:python-{{.VERSION}}"
    silent: true

  push:default:
    desc: "build and push akatsuki-default"
    dir: akatsuki-default
    cmds:
      - docker build -t akatsuki-default .
      - docker tag akatsuki-default tsuchiya55docker/akatsuki:default-{{.VERSION}}
      - docker push "tsuchiya55docker/akatsuki:default-{{.VERSION}}"
    silent: true

