version: '3'

vars:
  VERSION: 0.0.2

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:default:arm:
    desc: "build akatsuki-default-arm"
    dir: akatsuki-default-arm
    cmds:
      - docker build -t akatsuki-default-arm .
    silent: true

  run:default:arm:
    desc: "run akatsuki-default-arm (need build:default:arm before run this)"
    cmds:
      - bash ./entry_point.sh akatsuki-default-arm {{.CLI_ARGS}}
    silent: true

  build:default:amd:
    desc: "build akatsuki-default-amd"
    dir: akatsuki-default-amd
    cmds:
      - docker build -t akatsuki-default-amd .
    silent: true

  run:default:amd:
    desc: "run akatsuki-default-amd (need build:default:amd before run this)"
    cmds:
      - bash ./entry_point.sh akatsuki-default-arm {{.CLI_ARGS}}
    silent: true

  build:python:
    desc: "build akatsuki-python"
    dir: akatsuki-python
    cmds:
      - docker build -t akatsuki-python .
    silent: true

  run:python:
    desc: "run akatsuki-python (need build:python before run this)"
    cmds:
      - bash ./entry_point.sh akatsuki-python {{.CLI_ARGS}}
    silent: true

  push:
    desc: "build and push all containers"
    cmds:
      - task push:default:arm
      - task push:python

  push:python:
    desc: "build and push akatsuki-python"
    dir: akatsuki-python
    cmds:
      - docker build -t akatsuki-python .
      - docker tag akatsuki-python tsuchiya55docker/akatsuki:python-{{.VERSION}}
      - docker push "tsuchiya55docker/akatsuki:python-{{.VERSION}}"
    silent: true

  push:default:arm:
    desc: "build and push akatsuki-default"
    dir: akatsuki-default-arm
    cmds:
      - docker build -t akatsuki-default-arm .
      - docker tag akatsuki-default tsuchiya55docker/akatsuki:default-arm-{{.VERSION}}
      - docker push "tsuchiya55docker/akatsuki:default-arm-{{.VERSION}}"
    silent: true

