version: '3'

tasks:
  init:
    desc: Initialize the project by installing nix-darwin system-wide
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes nix-darwin -- switch --flake .#shunsock-darwin
      - echo "nix-darwin has been installed system-wide. darwin-rebuild command is now available."
    status:
      - which darwin-rebuild

  apply:
    desc: Apply the configuration with darwin-rebuild
    cmds:
      - bash script/remove_backup.sh
      - sudo darwin-rebuild switch --flake .#shunsock-darwin

  build:
    desc: Build and validate configuration without applying
    cmds:
      - nix build .#darwinConfigurations.shunsock-darwin.system

  check:
    desc: Validate flake configuration
    cmds:
      - nix flake check

  update:
    desc: Update flake dependencies
    cmds:
      - nix flake update

  validate:
    desc: Run comprehensive validation (build + check)
    deps:
      - build
      - check
