name: Go

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'homem/worker/**'

jobs:

  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./homem/worker
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

