name: nvimc_docker_build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'nvimc/**'
      - '.github/workflows/nvimc-build.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: nvimc-default-arm
            dockerfile: nvimc/nvimc-default-arm/Dockerfile
            context: nvimc/nvimc-default-arm
            platform: linux/arm64

          - name: nvimc-default-amd
            dockerfile: nvimc/nvimc-default-amd/Dockerfile
            context: nvimc/nvimc-default-amd
            platform: linux/amd64

          - name: nvimc-python
            dockerfile: nvimc/nvimc-python/Dockerfile
            context: nvimc/nvimc-python
            platform: linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: false
          load: true
          tags: ${{ matrix.name }}:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
